Try to fix Termux package installing problem

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -16,23 +16,23 @@ jobs:
         uses: pierotofy/set-swap-space@master
         with:
           swap-size-gb: 10
-      - name: Check version
-        run: |
-          sudo apt-get update
-          sudo apt install git curl
-          cd /home/runner
-          mkdir tmp
-          cd tmp
-          git clone https://github.com/tiann/KernelSU.git -b main
-          cd KernelSU
-          KSU_VER=$(expr 10000 + $(git rev-list --count HEAD) + 200)
-          if [ ${{ vars.KSU_LOCAL_VER }} -ge $KSU_VER ]; then
-            echo "::error::NO UPDATE!! (KSU_LOCAL_VER:${{ vars.KSU_LOCAL_VER }} is not less than KSU_VER:$KSU_VER), stopping workflow"
-            exit 1
-          fi
-          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TOKEN }} " -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Initsnow/kernelsu_xiaomi_polaris_action/actions/variables/KSU_LOCAL_VER -d '{"name":"KSU_LOCAL_VER","value":"'"${KSU_VER}"'"}'
-          echo "KSU_VER=${KSU_VER}" >> $GITHUB_ENV
-        shell: bash
+      # - name: Check version
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt install git curl
+      #     cd /home/runner
+      #     mkdir tmp
+      #     cd tmp
+      #     git clone https://github.com/tiann/KernelSU.git -b main
+      #     cd KernelSU
+      #     KSU_VER=$(expr 10000 + $(git rev-list --count HEAD) + 200)
+      #     if [ ${{ vars.KSU_LOCAL_VER }} -ge $KSU_VER ]; then
+      #       echo "::error::NO UPDATE!! (KSU_LOCAL_VER:${{ vars.KSU_LOCAL_VER }} is not less than KSU_VER:$KSU_VER), stopping workflow"
+      #       exit 1
+      #     fi
+      #     curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TOKEN }} " -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Initsnow/kernelsu_xiaomi_polaris_action/actions/variables/KSU_LOCAL_VER -d '{"name":"KSU_LOCAL_VER","value":"'"${KSU_VER}"'"}'
+      #     echo "KSU_VER=${KSU_VER}" >> $GITHUB_ENV
+      #   shell: bash
       - name: Setup build kernel environment
         run: |
           sudo apt-get update
@@ -41,7 +41,7 @@ jobs:
       - name: Download kernel source
         run: |
           cd /home/runner
-          git clone https://github.com/CZB666-wdnmd/android_kernel_xiaomi_sdm845.git -b udc --depth=1 kernel_sdm845
+          git clone https://github.com/Initsnow/android_kernel_xiaomi_sdm845.git -b lineage-21 --depth=1 kernel_sdm845
 
       - name: Download gcc and clang
         run: |
@@ -53,8 +53,8 @@ jobs:
       - name: Patch kernel source
         run: |
           cd /home/runner/kernel_sdm845
-          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s b766b98513b5a7eb33bc1c4a76b5702bf1288f07
-
+          # curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s b766b98513b5a7eb33bc1c4a76b5702bf1288f07
+          curl -LSs "https://raw.githubusercontent.com/Initsnow/KernelSU_Patch/main/kernel/setup.sh" | bash -s main
       - name: Build
         run: |
           cd /home/runner/kernel_sdm845
